<?php
/**
 * Title: Ugolini discovery links
 * Slug: ugolini-group/discovery-cta
 * Categories: ugolini-sections
 * Keywords: shop, faq, blog, calls to action
 */
?>
<!-- wp:group {"align":"full","className":"ugolini-discovery ugolini-section","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-discovery ugolini-section"><!-- wp:html --><figure class="ugolini-discovery-art" aria-hidden="true"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/home/discovery-truffles.jpg' ) ); ?>" alt=""></figure><!-- /wp:html --><!-- wp:group {"align":"wide","layout":{"type":"default"}} --><div class="wp-block-group alignwide"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Dentro il mondo Ugolini</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Scopri, scegli, cucina</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Tre percorsi per conoscere le specialità, trovare risposte e lasciarsi ispirare.</p><!-- /wp:paragraph --><!-- wp:group {"className":"ugolini-discovery-grid","layout":{"type":"default"}} --><div class="wp-block-group ugolini-discovery-grid">
<!-- wp:cover {"url":"https://ugolinigroup.com/wp-content/uploads/2026/08/8800-pesto-alla-genovese-ugolini-gourmet-10.jpg","alt":"Pesto alla genovese Ugolini Gourmet","dimRatio":58,"overlayColor":"dark-section","isUserOverlayColor":true,"className":"ugolini-discovery-card"} --><div class="wp-block-cover ugolini-discovery-card"><span aria-hidden="true" class="wp-block-cover__background has-dark-section-background-color has-background-dim-60 has-background-dim"></span><img class="wp-block-cover__image-background" alt="Pesto alla genovese Ugolini Gourmet" src="https://ugolinigroup.com/wp-content/uploads/2026/08/8800-pesto-alla-genovese-ugolini-gourmet-10.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Prodotti</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Esplora le specialità</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Sughi, pesti, tartufi e condimenti della gamma Ugolini Gourmet.</p><!-- /wp:paragraph --><!-- wp:button {"className":"is-style-outline-light"} --><div class="wp-block-button is-style-outline-light"><a class="wp-block-button__link wp-element-button" href="/shop/">Vai allo shop</a></div><!-- /wp:button --></div></div><!-- /wp:cover -->
<!-- wp:cover {"url":"https://ugolinigroup.com/wp-content/uploads/2026/08/8831-sugo-tartufo-nero-ugolini-gourmet-7.jpg","alt":"Sugo al tartufo Ugolini Gourmet","dimRatio":62,"overlayColor":"dark-section","isUserOverlayColor":true,"className":"ugolini-discovery-card"} --><div class="wp-block-cover ugolini-discovery-card"><span aria-hidden="true" class="wp-block-cover__background has-dark-section-background-color has-background-dim-60 has-background-dim"></span><img class="wp-block-cover__image-background" alt="Sugo al tartufo Ugolini Gourmet" src="https://ugolinigroup.com/wp-content/uploads/2026/08/8831-sugo-tartufo-nero-ugolini-gourmet-7.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Supporto</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Le risposte che cerchi</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Informazioni essenziali sui prodotti e sulle richieste professionali.</p><!-- /wp:paragraph --><!-- wp:button {"className":"is-style-outline-light"} --><div class="wp-block-button is-style-outline-light"><a class="wp-block-button__link wp-element-button" href="/faq/">Consulta le FAQ</a></div><!-- /wp:button --></div></div><!-- /wp:cover -->
<!-- wp:cover {"url":"https://ugolinigroup.com/wp-content/uploads/2026/08/8886-pesto-rosso-bio-ugolini-gourmet-9-scaled-1.jpg","alt":"Pesto rosso biologico Ugolini Gourmet","dimRatio":62,"overlayColor":"dark-section","isUserOverlayColor":true,"className":"ugolini-discovery-card"} --><div class="wp-block-cover ugolini-discovery-card"><span aria-hidden="true" class="wp-block-cover__background has-dark-section-background-color has-background-dim-60 has-background-dim"></span><img class="wp-block-cover__image-background" alt="Pesto rosso biologico Ugolini Gourmet" src="https://ugolinigroup.com/wp-content/uploads/2026/08/8886-pesto-rosso-bio-ugolini-gourmet-9-scaled-1.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Ispirazione</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Storie dalla cucina</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Idee, tecniche e racconti dedicati al gusto italiano.</p><!-- /wp:paragraph --><!-- wp:button {"className":"is-style-outline-light"} --><div class="wp-block-button is-style-outline-light"><a class="wp-block-button__link wp-element-button" href="/blog/">Leggi il blog</a></div><!-- /wp:button --></div></div><!-- /wp:cover -->
</div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:group -->
