<?php
/**
 * Title: La storia Ugolini
 * Slug: ugolini-group/home-story
 * Categories: ugolini-sections
 * Keywords: storia, chi siamo, heritage
 */
?>
<!-- wp:group {"align":"full","className":"ugolini-home-story","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull ugolini-home-story">
<!-- wp:group {"align":"wide","className":"ugolini-home-story__row","layout":{"type":"default"}} --><div class="wp-block-group alignwide ugolini-home-story__row"><!-- wp:group {"className":"ugolini-home-story__copy","layout":{"type":"constrained"}} --><div class="wp-block-group ugolini-home-story__copy"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Una storia di famiglia</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Le radici di una passione italiana</h2><!-- /wp:heading --><!-- wp:paragraph --><p>La storia di Ugolini nasce nei primi anni del Novecento dalla passione di nonno Renato, coltivatore e fondatore della prima attività agricola di famiglia. Sua figlia Renata portava personalmente il raccolto al mercato, custodendo un rapporto diretto con il cibo fresco e naturale.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Roberto cresce dentro questa cultura familiare. Dopo oltre un secolo di esperienza condivisa prende forma Ugolini Gourmet, dove memoria gastronomica e ricerca contemporanea si incontrano.</p><!-- /wp:paragraph --><p class="ugolini-editorial-link"><a href="/shop/">Esplora i prodotti</a></p></div><!-- /wp:group --><!-- wp:group {"className":"ugolini-home-story__gallery","layout":{"type":"default"}} --><div class="wp-block-group ugolini-home-story__gallery"><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="https://ugolinigroup.com/wp-content/uploads/2026/08/8824-ragu-alla-bolognese-ugolini-gourmet-10.jpg" alt="Ragù Ugolini Gourmet con pomodori"/></figure><!-- /wp:image --><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="https://ugolinigroup.com/wp-content/uploads/2026/08/8817-pesto-rosso-ugolini-gourmet-4.jpg" alt="Pesto rosso Ugolini Gourmet"/></figure><!-- /wp:image --></div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:group {"align":"wide","className":"ugolini-home-story__row ugolini-home-story__row--reverse","layout":{"type":"default"}} --><div class="wp-block-group alignwide ugolini-home-story__row ugolini-home-story__row--reverse"><!-- wp:group {"className":"ugolini-home-story__gallery","layout":{"type":"default"}} --><div class="wp-block-group ugolini-home-story__gallery"><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="https://ugolinigroup.com/wp-content/uploads/2026/08/8848-sugo-allarrabbiata-ugolini-gourmet-5.jpg" alt="Sugo all’arrabbiata Ugolini Gourmet"/></figure><!-- /wp:image --><!-- wp:image {"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="https://ugolinigroup.com/wp-content/uploads/2026/08/8831-sugo-tartufo-nero-ugolini-gourmet-7.jpg" alt="Sugo al tartufo nero Ugolini Gourmet"/></figure><!-- /wp:image --></div><!-- /wp:group --><!-- wp:group {"className":"ugolini-home-story__copy","layout":{"type":"constrained"}} --><div class="wp-block-group ugolini-home-story__copy"><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Esperienza e innovazione</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Dalla ristorazione a una linea gourmet</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Con oltre vent’anni di esperienza nella ristorazione e il confronto con chef stellati, Roberto Ugolini ha trasformato esigenze reali di cucina in prodotti affidabili, funzionali e riconoscibili.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Dalla collaborazione con lo chef Nino Cannavale nasce la prima linea di salse gourmet e al tartufo. La gamma si sviluppa per cucine professionali, distribuzione e famiglie, con una particolare attenzione alla continuità del risultato.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Proposte vegane e biologiche e specifiche referenze Halal o Kosher ampliano la scelta: certificazioni e caratteristiche restano sempre associate al singolo prodotto.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:group {"align":"wide","className":"ugolini-home-story__manifesto","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide ugolini-home-story__manifesto"><!-- wp:html --><figure class="ugolini-home-story__family" data-story-reveal><img src="/wp-content/themes/ugolini-group/assets/images/ugolini-family.png" alt="La famiglia Ugolini riunita davanti a un edificio storico" width="1264" height="848" loading="lazy" decoding="async"></figure><!-- /wp:html --><!-- wp:paragraph {"className":"ugolini-eyebrow"} --><p class="ugolini-eyebrow">Ugolini Gourmet</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Tradizione, esperienza e innovazione per portare in tavola un gusto autentico.</h2><!-- /wp:heading --></div><!-- /wp:group -->
</div><!-- /wp:group -->
